version: "3"

services:
  app:
    build: 
      context: .
    depends_on:
      - postgres
    networks:
      - backend
    ports: 
      - "5000:5000"
    # volumes: 
    # # use "COPY" in dockerfile will be better for real scenario
    # # as it allows the developer to to control the versions based on the changes
    #   # - /home/tan/Desktop/besquare-drc/cryptown-backend:/usr/src/app
    #   - .:/usr/src/app
    # tty: true
    command: [sh, -c, "npm start && echo ${POSTGRES_PORT}"]
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: cryptown_nodejs
    

  postgres:
    restart: always
    image: postgres:13-alpine
    networks:
      - backend
    volumes: 
      - ../db_mount:/var/lib/postgresql/data
      - ./db_init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: cryptown_postgres

networks:
  backend:


# add in networks, volumes, ports, postgres environment variables  