name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: create .env file
      run: |
        touch .env
        echo 'PORT=${{ secrets.PORT }}' >> .env
        echo 'BING_NEWS_TOKEN=${{ secrets.BING_NEWS_TOKEN }}' >> .env
        echo 'POSTGRES_PASS=${{ secrets.POSTGRES_PASS }}' >> .env
        echo 'POSTGRES_USER=${{ secrets.POSTGRES_USER }}' >> .env
        echo 'POSTGRES_DB=${{ secrets.POSTGRES_DB }}' >> .env
        echo 'POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}' >> .env
    - name: Build the Docker image
      run: docker compose --env-file .env up --build -d
