name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: create .env file
      run: |
        touch .env
        echo 'PORT=${{ secrets.PORT }}' >> .env
        echo 'POSTGRES_PASS=${{ secrets.POSTGRES_PASS }}' >> .env
        echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> .env
        echo 'BING_NEWS_TOKEN=${{ secrets.BING_NEWS_TOKEN }}' >> .env
    - name: Build the Docker image
      run: docker compose --env-file .env up --build -d
    - name: get runner groups
      run: id
    - name: check file owner
      run: ls -la
