name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: create .env file
      run: |
        touch .env
        echo 'PORT=${{ PORT }}' >> .env
        echo 'POSTGRES_PASS=${{ POSTGRES_PASS }}' >> .env
        echo 'JWT_SECRET=${{ JWT_SECRET }}' >> .env
        echo 'BING_NEWS_TOKEN=${{ BING_NEWS_TOKEN }}' >> .env
    - name: Build the Docker image
      run: docker compose --env-file .env up --build -d
